apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: luiishs/qualentum_app1:0.1.0
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-service"

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP 
