apiVersion: apps/v1 # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1 # https://kubernetes.io/es/docs/concepts/workloads/controllers/replicaset#cu%C3%A1ndo-usar-un-replicaset
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP # https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/
