Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.hostname = "local.qualentum.org"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
    end

  # colocamos en la primera ruta la carpeta que contenga el archivo app.py del proyecto para poder copiarlo fácil dentro de vagrant. En mi caso es el escritorio
    config.vm.synced_folder "C:/Users/luiis/Desktop", "/home/vagrant/sync"

  # aprovisionamiento
    config.vm.provision "shell", inline: <<-SHELL

    sudo apt update

  # todos los aprovisionamientos se instalarán solo si no lo están
  if ! command -v curl > /dev/null; then
    sudo apt install -y curl
  fi

  if ! command -v vim > /dev/null; then
    sudo apt install -y vim
  fi

  if ! command -v nginx > /dev/null; then
    sudo apt install -y nginx
  fi

  if ! command -v pip3 > /dev/null; then
    sudo apt install -y python3-pip
  fi

  if ! python3 -m pip show flask > /dev/null 2>&1; then
    pip3 install gunicorn flask werkzeug
  fi

  # certificados ssl. Contiene una gestión de permisos como corrección de errores
  if [ ! -f /home/vagrant/cert.pem ] || [ ! -f /home/vagrant/key.pem ]; then
    openssl req -x509 -newkey rsa:4096 -nodes -out /home/vagrant/cert.pem -keyout /home/vagrant/key.pem -days 365 -subj "/CN=local.qualentum.org"

    sudo chmod 644 /home/vagrant/cert.pem /home/vagrant/key.pem
  fi

  # genera en la carpeta descrita un archivo que contendrá el reverse proxy encargado de redirigir el tráfico a peticiones http a https.
  # crea un nuevo archivo en llamado flask_app y borra la carpeta default para evitar conflictos producidos en tests
if [ ! -f /etc/nginx/sites-available/flask_app ]; then
  cat <<'EOF' | sudo tee /etc/nginx/sites-available/flask_app > /dev/null
  server {
      listen 443 ssl;
      server_name local.qualentum.org;

      ssl_certificate     /home/vagrant/cert.pem;
      ssl_certificate_key /home/vagrant/key.pem;

      location / {
          proxy_pass http://localhost:8888;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
  }

  server {
      listen 80;
      server_name local.qualentum.org;

      return 301 https://$host$request_uri;
  }
EOF

      sudo ln -s /etc/nginx/sites-available/flask_app /etc/nginx/sites-enabled/
      sudo rm -f /etc/nginx/sites-enabled/default
      sudo nginx -t && sudo systemctl restart nginx
    fi
  SHELL
end
