---
- name: Install LAMP WEB Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: present
  loop: ['apache2', 'php', 'php-mysql', 'libapache2-mod-php']

- name: Add the user '{{ app_user }}' as a part of the httpd group
  ansible.builtin.user:
    name: "{{ app_user }}"

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Set up Apache virtualhost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: Reload Apache

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache

- name: "Iptables - Allow HTTP on port {{ http_port }}"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port:  "{{ http_port }}"

- name: Sets Up PHP Info Page
  template:
    src: "files/info.php.j2"
    dest: "/var/www/{{ http_host }}/index.php"