Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false # Avoids the need for SSH keys to simplify access

  # Bastion
  config.vm.define "bastion" do |bastion|
    bastion.vm.hostname = "bastion.local"
    bastion.vm.network "private_network", ip: "192.168.19.100"
    bastion.vm.network "private_network", ip: "192.168.20.100"

    # Provisioning script
    bastion.vm.provision "shell", inline: <<-SHELL
      sudo sysctl -w net.ipv4.ip_forward=1 # Enable IP forwarding
      sudo apt-get install -y tcpdump   # tcpdump
      sudo iptables -A FORWARD -s 172.16.1.0/24 -d 172.16.2.0/24 -j ACCEPT # Allow traffic between subnets
      sudo iptables -A FORWARD -s 172.16.2.0/24 -d 172.16.1.0/24 -j ACCEPT
    SHELL
  end

  # Web1
  config.vm.define "web1" do |web|
    web.vm.hostname = "web1.local"
    web.vm.network "private_network", ip: "192.168.19.2"
    web.vm.network "private_network", ip: "172.16.1.2"

    # Provisioning script
    web.vm.provision "shell", inline: <<-SHELL
      sudo ip route add 172.16.2.0/24 via 192.168.19.100 # Add route to web2
    SHELL
  end

  # Web2
  config.vm.define "web2" do |web|
    web.vm.hostname = "web2.local"
    web.vm.network "private_network", ip: "192.168.20.2"
    web.vm.network "private_network", ip: "172.16.2.2"

    # Provisioning script
    web.vm.provision "shell", inline: <<-SHELL
      sudo ip route add 172.16.1.0/24 via 192.168.20.100 # Add route to web1
    SHELL
  end

  # Virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
end