#!/bin/bash
# script que se ejecuta en cada máquina virtual para configurar un servidor web básico
# diferentes echo's para el log y depuración en log vagrant
echo "Starting provision_web.sh"

sudo apt-get update
sudo apt-get install -y nginx

echo "Nginx installed"

# Crear el directorio /var/www/html si no existe
sudo mkdir -p /var/www/html

# bienvenida simple

echo "Hello from $(hostname)" | sudo tee /var/www/html/index.html
echo "Page created"

# permite el tráfico SSH y HTTP
sudo ufw allow 22  # SSH
sudo ufw allow 80  # HTTP
sudo ufw --force enable

echo "Firewall configured"