pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
        BUCKET_NAME = 'jenkins-test'
        FILE_NAME = 'fichero.txt'
        DOWNLOADED_FILE = 'fichero_descargado.txt'
    }
    stages {
        stage('configuramos aws') {
            steps {
                withAWS(credentials: 'aws-jenkins', region: env.AWS_REGION) { // usamos credenciales aws
                    sh "aws s3 mb s3://${BUCKET_NAME} || true" // creación del bucket
                }
            }
        }

        stage('creamos y subimos el archivo') {
            steps {
                script {
                    sh "echo 'Hola!!' > ${FILE_NAME}"
                }
                withAWS(credentials: 'aws-jenkins', region: env.AWS_REGION) {
                    s3Upload(file: FILE_NAME, bucket: BUCKET_NAME, path: FILE_NAME) // subimos el archivo usando el plugin
                }
            }
        }

        stage('descargamos el archivo desde S3') {
            steps {
                withAWS(credentials: 'aws-jenkins', region: env.AWS_REGION) {
                    s3Download(file: DOWNLOADED_FILE, bucket: BUCKET_NAME, path: FILE_NAME)  // descargamos
                }
                sh "cat ${DOWNLOADED_FILE}"  //verificamos que se descargó
        }

        stage('creamos una instancia ec2 (testing)') {
            steps {
                withAWS(credentials: 'aws-jenkins', region: env.AWS_REGION) {
                    sh 'aws ec2 run-instances --image-id ami-0c55b159cbfafe1f0 --instance-type t2.micro --count 1'
                }
            }
        }
    }
}
