name: Python CI Resta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_resta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run test for resta
        run: |
          python -m unittest test_resta.py